### PR TITLE
Send 'X-Ajax-Browser-Auth' header on requests

### PR DESCRIPTION
**Pull request by oskarhane**
- To tell server that we want to be treated
  with special response headers.

### CODE REVIEW

**Comment by oskarhane** [comment]
Would @cleishm and @jakewins comment on this, please?  
It's this card: https://trello.com/c/cOaZgCt4

**Comment by cleishm** [comment]
Is there any way to automatically test this kind of thing? The next step would be to change the server to send a known WWW-Auth header if it _doesnt_ see this X-AJAX-BROWSER-AUTH header. That'll break the browser if the header is ever missing, so a regression test would be nice.

**Comment by oskarhane** [comment]
@cleishm The test in this PR will check that the header is there.  
All requests are intercepted and get the header added, and the test illustrates that this works when POST:ing Cypher queries.  

I'm not sure what other test you mean.

**Comment by cleishm** [comment]
Ooops. I didn't notice that was a test. Just looked like more coffeescript to me ;-)

LGTM

**Pull request merged**
